### PR TITLE
#157754177 Creating User/Admin Log in Page

### PR DESCRIPTION
**Pull request by janetnim**
**What does this PR do?**
Create a log in page

**Description of Task to be completed?**
A log in form should be designed with username/email and password fields

**How should this be manually tested?**
After adding the html and css files to the UI directory, open the login.html file in your browser to see if all components of the page appear and work as they should

**# What are the relevant pivotal tracker stories?**
#157754177

### CODE REVIEW

**Comment by gtsofa** [comment]
Kindly make sure you merge commits into **develop** from **feature** first. You're currently merging commits into master from feature on this PR.

**Comment by PaulKitonyi** [comment]
Please avoid Merging into master.Consider creating a develop branch to merge into instead.Also avoid white spaces in your snippets.

**Comment by mmosoroohh** [comment]
You should have a **develop** branch. Where you will merge you feature to it.

**Comment by johnmusiu** [comment]
I suppose the tracker stories section should include a **click-able link to your PT story.

**Pull request merged**
